resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/14/27.yaml

packages:
- hedgehog
- hedgehog-corpus
- hedgehog-dieharder
- hedgehog-example
- hedgehog-quickcheck
- hedgehog-test-laws
